---
- name: Install Apache
  hosts: automation
  become: yes

  tasks:
    - name: Install Apache2 and LibApache2 packages for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
