---
- name: Install Apache
  hosts: automation
  become: yes

  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install Apache
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "CentOS"

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "CentOS"
